version: '3.9'

services:
  swapi-dev:
    container_name: swapi-backend-dev
    profiles:
      - dev
    build:
      context: .
      dockerfile: dockerfile
      target: builder
    mem_limit: 1024m
    command: ["yarn", "start:dev"]
    environment:
      - NODE_PORT=${NODE_PORT?err}
    ports:
      - "3000:${NODE_PORT}"
    depends_on:
      - redis
    volumes:
      - .:/app
      - /src/node_modules

  redis: 
    container_name: redis
    profiles: 
      - dev
    image: redis:alpine
    ports:
      - 6379:6379
    hostname: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD?err}
    command: >
      --requirepass ${REDIS_PASSWORD?err}